#!/usr/bin/env python3
"""Generate the contrast fixture with EXACT known ground truth.

This is the fixture from the hardening brief, reproduced verbatim so the
reference numbers in its table can be checked against real generated bytes.

    python3 verify/make-fixture.py     # writes fixture.png in the repo root
"""
from PIL import Image, ImageDraw, ImageFont

W, H = 900, 420
BG = (26, 24, 20)  # #1a1814
img = Image.new("RGB", (W, H), BG)
d = ImageDraw.Draw(img)


def font(sz):
    for p in ("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
              "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf"):
        try:
            return ImageFont.truetype(p, sz)
        except OSError:
            pass
    return ImageFont.load_default()


# 1. Large, high contrast (~13.4:1) -- must be read correctly.
d.text((30, 26), "ALPHA-ONE", fill=(232, 223, 208), font=font(40))
# 2. Large, LOW contrast (~2.14:1) -- must be FLAGGED as failing.
d.text((30, 96), "BRAVO-TWO", fill=(72, 79, 88), font=font(40))
# 3. Small text, good contrast -- tests fine-text legibility.
d.text((30, 168), "CHARLIE-THREE-8g7x2", fill=(160, 149, 136), font=font(13))
# 4. Exactly FOUR evenly spaced boxes; only ECHO carries a plus.
for i, lab in enumerate(("DELTA", "ECHO", "FOXTROT", "GOLF")):
    x = 30 + i * 215
    d.rectangle([x, 220, x + 190, 330], outline=(74, 67, 60), width=2)
    d.text((x + 18, 240), lab, fill=(232, 223, 208), font=font(22))
    d.text((x + 18, 285), "mark " + ("+" if lab == "ECHO" else "-"),
           fill=(125, 170, 122), font=font(17))
# 5. Effectively invisible (~1.04:1) -- must NOT be reported as readable text.
d.text((30, 372), "HOTEL-FIVE-INVISIBLE", fill=(30, 28, 24), font=font(30))

img.save("fixture.png")
print("wrote fixture.png", img.size)
